# Generated by Django 6.0.6 on 2026-06-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas_animais",
                to="clinica.animal",
            ),
        ),
    ]
