# Generated by Django 6.0.6 on 2026-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0002_alter_consulta_animal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veterinario",
            name="especialidade",
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "veterinarios",
                    models.ManyToManyField(
                        related_name="veterinarios", to="clinica.veterinario"
                    ),
                ),
            ],
        ),
    ]
