# Generated by Django 6.0.6 on 2026-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0003_remove_veterinario_especialidade_especialidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="especialidade",
            name="veterinarios",
            field=models.ManyToManyField(
                related_name="especialidades", to="clinica.veterinario"
            ),
        ),
    ]
