# Generated by Django 6.0.6 on 2026-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "atletas",
                    models.ManyToManyField(
                        related_name="categorias", to="torneio.atleta"
                    ),
                ),
            ],
        ),
    ]
