# Generated by Django 6.0.6 on 2026-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneio", "0002_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="torneio",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
